[project]
name = "azure-deploy"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity==1.14.1",
    "azure-mgmt-web==7.1.0",
    "azure-storage-file-share==12.14.2",
    "fastapi==0.109.0",
    "pydantic==2.5.3",
    "python-dotenv==1.0.0",
    "requests==2.31.0",
    "uvicorn==0.27.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]


[tool.basedpyright]
typeCheckingMode = "basic"
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
useLibraryCodeForTypes = true

[tool.ruff]
select = ["E", "F", "T20", "I001"]
ignore = ["E402", "E501"]
fixable = ["E", "F", "I001"]

