version: "3"

services:
  app:
    image: sagittarius.azurecr.io/grafana_dashboard:latest
    # dockerfile: Dockerfile
    build: .
    user: "472"
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      URL_CONFIG: ${URL_CONFIG}
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: smartcomm-bulletgraph-panel,smartcomm-calendar-panel,smartcomm-extremevalues-panel,smartcomm-map-panel,smartcomm-multiplelinechart-panel,smartcomm-simpleline-panel,smartcomm-minmaxbarchart-panel
      GF_FEATURE_TOGGLES_ENABLE: transformationsVariableSupport
    ports:
      - "3000:3000"
